# .github/workflows/main.yml
name: Main Taski workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    # Разворачиваем окружение:
    runs-on: ubuntu-latest

    steps:
    # Копируем код проекта
    - name: Check out code
      uses: actions/checkout@v3
    # Устанавливаем Python с помощью action
    - name: Set up Python
      uses: actions/setup-python@v4
    # В action setup-python@v4 передаём параметр — версию Python
      with:
        python-version: 3.12             
    # Обновляем pip, устанавливаем flake8 и flake8-isort, 
    # устанавливаем зависимости проекта
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade flake8 flake8-isort setuptools wheel
        pip install -r ./backend/requirements.txt                
    # Запускаем flake8
    - name: Run flake8
      run: |
        python -m flake8 backend/
    # Запускаем django tests (через docker-compose)    
    - name: Run Django tests
      run: |
        cd backend/
        python manage.py test